name: GitHub CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # correct build machine timezone
      - run: sudo timedatectl set-timezone Asia/Shanghai
      # checkout source
      - name: Checkout
        uses: actions/checkout@v2
      # setup node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      # find yarn cache
      - name: Get yarn cache path
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      # update cache
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      # generate artifacts
      - run: yarn install
      - run: yarn build
      # deployment
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # use github actions bot as committer
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          # docs: https://developer.github.com/v3/activity/events/types/#commitcommentevent
          commit_message: site updated at ${{ github.event.head_commit.timestamp }}
